Support GPU enabled CI
Some builds depend on GPU support. A new Github Runner has been added
that supports GPUs. This change will run tests specifically requiring
GPU support to run on GPU enabled runners.

(cherry picked from commit 06bc63329a2b6a0a3fdffa784cea90128c7276e6)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -2243,6 +2243,50 @@ jobs:
           conclusion: ${{ job.status }}
           github_token: ${{ secrets.GITHUB_TOKEN }}
 
+  gpu-tests:
+    runs-on: [self-hosted, gha-fleet-ec2-1GPU-16CPU-64GB-amd64, latest]
+    if: |
+      github.event_name != 'pull_request' ||
+      contains(github.event.pull_request.labels.*.name, 'gpu')
+    timeout-minutes: 30
+    steps:
+      - uses: actions/checkout@v6
+        with:
+          fetch-depth: 0
+          ref: |
+            ${{ github.event_name == 'repository_dispatch' &&
+                github.event.client_payload.pull_request.head.sha == github.event.client_payload.slash_command.args.named.sha &&
+                format('refs/pull/{0}/head', github.event.client_payload.pull_request.number) || '' }}
+      - name: Set up AWS code-artifacts and ECR login
+        uses: ./.github/actions/starburst-setup
+        with:
+          aws-access-key-id: ${{ vars.ENG_AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.ENG_AWS_SECRET_ACCESS_KEY }}
+          secret-id: ${{ vars.SEP_SECRETS_AWS_ID }}
+          login-docker: true
+      - uses: ./.github/actions/setup
+      # TODO (https://starburstdata.atlassian.net/browse/ENG-12575) remove this once we have an AMI with GPU drivers pre-installed
+      - name: Install GPU drivers
+        run: |
+          .github/bin/retry sudo apt update
+          .github/bin/retry sudo apt install -y ubuntu-drivers-common
+          .github/bin/retry sudo apt install -y --no-install-recommends \
+            nvidia-headless-no-dkms-595-server \
+            nvidia-utils-595-server \
+            libnvidia-compute-595-server \
+            linux-modules-nvidia-595-server-$(uname -r)
+          sudo modprobe nvidia
+      - name: Maven Install
+        run: |
+          export MAVEN_OPTS="${MAVEN_INSTALL_OPTS}"
+          $MAVEN clean install -DskipTests -Dmaven.javadoc.skip=true -Dmaven.source.skip=true -Dair.check.skip-all=true -Dskip.npm -Dskip.yarn -pl :trino-main,:trino-hive,:trino-tests -am
+      - name: Maven Tests - core/trino-main
+        run: $MAVEN test ${MAVEN_TEST} -pl core/trino-main -P gpu
+      - name: Maven Tests - plugin/trino-hive
+        run: $MAVEN test ${MAVEN_TEST} -pl plugin/trino-hive -P gpu
+      - name: Maven Tests - testing/trino-tests
+        run: $MAVEN test ${MAVEN_TEST} -pl testing/trino-tests -P gpu
+
   build-pt:
     needs: path-filters
     if: github.event_name != 'pull_request' || needs.path-filters.outputs.non_docs == 'true'
@@ -2728,6 +2772,7 @@ jobs:
       - check-commits-dispatcher
       - error-prone-checks
       - google-sheets-tests
+      - gpu-tests
       - hive-tests
       - maven-checks
       - path-filters
@@ -2757,6 +2802,7 @@ jobs:
           echo '${{ needs.check-commits-dispatcher.result }}' | grep -xE 'success|skipped' || { echo 'Job "check-commits-dispatcher" failed' >&2; exit 1; }
           echo '${{ needs.error-prone-checks.result }}' | grep -xE 'success|skipped' || { echo 'Job "error-prone-checks" failed' >&2; exit 1; }
           echo '${{ needs.google-sheets-tests.result }}' | grep -xE 'success|skipped' || { echo 'Job "google-sheets-tests" failed' >&2; exit 1; }
+          echo '${{ needs.gpu-tests.result }}' | grep -xE 'success|skipped' || { echo 'Job "gpu-tests" failed' >&2; exit 1; }
           echo '${{ needs.hive-tests.result }}' | grep -xE 'success|skipped' || { echo 'Job "hive-tests" failed' >&2; exit 1; }
           echo '${{ needs.maven-checks.result }}' | grep -xE 'success|skipped' || { echo 'Job "maven-checks" failed' >&2; exit 1; }
           echo '${{ needs.path-filters.result }}' | grep -xE 'success|skipped' || { echo 'Job "path-filters" failed' >&2; exit 1; }
