Have build-success as the last job in the workflow
Because it's the last one to run.

(cherry picked from commit 7f245484f235f3ee76e369b20ee3e3e3c38bc1a9)
(cherry picked from commit 6238e6a052505d63601a5b0bd067ae85f27ef24b)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -57,56 +57,6 @@ concurrency:
     commit_sha=${{ github.event_name != 'pull_request' && github.event_name != 'repository_dispatch' && github.sha || 'NA' }}
   cancel-in-progress: true
 jobs:
-  build-success:
-    if: ${{ always() }} # if `failure()` would not work for cancellations, `!success()` would not work for skipped jobs
-    runs-on: [self-hosted, gha-fleet-ec2-2cpu-8gb-amd64, latest]
-    needs:
-      - artifact-checks
-      - build-pt
-      - build-test-matrix
-      - check-commit
-      - check-commits-dispatcher
-      - error-prone-checks
-      - hive-tests
-      - maven-checks
-      - pt
-      - redshift-cloud-tests
-      - redshift-fte-tests
-      - salesforce-tests
-      - snowflake-nightly-tests
-      - snowflake-weekly-tests
-      - starburst-functions-ai-tests
-      - synapse-nightly-tests
-      - synapse-weekly-tests
-      - test
-      - test-jdbc-compatibility
-      - test-other-modules
-    steps:
-      - name: "Check results"
-        run: |
-          # generated by TestStarburstWorkflows
-          # generated by TestCiWorkflow
-          echo '${{ needs.artifact-checks.result }}' | grep -xE 'success|skipped' || { echo 'Job "artifact-checks" failed' >&2; exit 1; }
-          echo '${{ needs.build-pt.result }}' | grep -xE 'success|skipped' || { echo 'Job "build-pt" failed' >&2; exit 1; }
-          echo '${{ needs.build-test-matrix.result }}' | grep -xE 'success|skipped' || { echo 'Job "build-test-matrix" failed' >&2; exit 1; }
-          echo '${{ needs.check-commit.result }}' | grep -xE 'success|skipped' || { echo 'Job "check-commit" failed' >&2; exit 1; }
-          echo '${{ needs.check-commits-dispatcher.result }}' | grep -xE 'success|skipped' || { echo 'Job "check-commits-dispatcher" failed' >&2; exit 1; }
-          echo '${{ needs.error-prone-checks.result }}' | grep -xE 'success|skipped' || { echo 'Job "error-prone-checks" failed' >&2; exit 1; }
-          echo '${{ needs.hive-tests.result }}' | grep -xE 'success|skipped' || { echo 'Job "hive-tests" failed' >&2; exit 1; }
-          echo '${{ needs.maven-checks.result }}' | grep -xE 'success|skipped' || { echo 'Job "maven-checks" failed' >&2; exit 1; }
-          echo '${{ needs.pt.result }}' | grep -xE 'success|skipped' || { echo 'Job "pt" failed' >&2; exit 1; }
-          echo '${{ needs.redshift-cloud-tests.result }}' | grep -xE 'success|skipped' || { echo 'Job "redshift-cloud-tests" failed' >&2; exit 1; }
-          echo '${{ needs.redshift-fte-tests.result }}' | grep -xE 'success|skipped' || { echo 'Job "redshift-fte-tests" failed' >&2; exit 1; }
-          echo '${{ needs.salesforce-tests.result }}' | grep -xE 'success|skipped' || { echo 'Job "salesforce-tests" failed' >&2; exit 1; }
-          echo '${{ needs.snowflake-nightly-tests.result }}' | grep -xE 'success|skipped' || { echo 'Job "snowflake-nightly-tests" failed' >&2; exit 1; }
-          echo '${{ needs.snowflake-weekly-tests.result }}' | grep -xE 'success|skipped' || { echo 'Job "snowflake-weekly-tests" failed' >&2; exit 1; }
-          echo '${{ needs.starburst-functions-ai-tests.result }}' | grep -xE 'success|skipped' || { echo 'Job "starburst-functions-ai-tests" failed' >&2; exit 1; }
-          echo '${{ needs.synapse-nightly-tests.result }}' | grep -xE 'success|skipped' || { echo 'Job "synapse-nightly-tests" failed' >&2; exit 1; }
-          echo '${{ needs.synapse-weekly-tests.result }}' | grep -xE 'success|skipped' || { echo 'Job "synapse-weekly-tests" failed' >&2; exit 1; }
-          echo '${{ needs.test.result }}' | grep -xE 'success|skipped' || { echo 'Job "test" failed' >&2; exit 1; }
-          echo '${{ needs.test-jdbc-compatibility.result }}' | grep -xE 'success|skipped' || { echo 'Job "test-jdbc-compatibility" failed' >&2; exit 1; }
-          echo '${{ needs.test-other-modules.result }}' | grep -xE 'success|skipped' || { echo 'Job "test-other-modules" failed' >&2; exit 1; }
-
   maven-checks:
     runs-on: [self-hosted, gha-fleet-ec2-4cpu-16gb-amd64, latest]
     name: maven-checks ${{ matrix.java-version }}
@@ -2291,3 +2241,52 @@ jobs:
           check_name: ${{ github.job }} with secrets
           conclusion: ${{ job.status }}
           github_token: ${{ secrets.GITHUB_TOKEN }}
+
+  build-success:
+    if: ${{ always() }} # if `failure()` would not work for cancellations, `!success()` would not work for skipped jobs
+    runs-on: [self-hosted, gha-fleet-ec2-2cpu-8gb-amd64, latest]
+    needs:
+      - artifact-checks
+      - build-pt
+      - build-test-matrix
+      - check-commit
+      - check-commits-dispatcher
+      - error-prone-checks
+      - hive-tests
+      - maven-checks
+      - pt
+      - redshift-cloud-tests
+      - redshift-fte-tests
+      - salesforce-tests
+      - snowflake-nightly-tests
+      - snowflake-weekly-tests
+      - starburst-functions-ai-tests
+      - synapse-nightly-tests
+      - synapse-weekly-tests
+      - test
+      - test-jdbc-compatibility
+      - test-other-modules
+    steps:
+      - name: "Check results"
+        run: |
+          # generated by TestCiWorkflow
+          echo '${{ needs.artifact-checks.result }}' | grep -xE 'success|skipped' || { echo 'Job "artifact-checks" failed' >&2; exit 1; }
+          echo '${{ needs.build-pt.result }}' | grep -xE 'success|skipped' || { echo 'Job "build-pt" failed' >&2; exit 1; }
+          echo '${{ needs.build-test-matrix.result }}' | grep -xE 'success|skipped' || { echo 'Job "build-test-matrix" failed' >&2; exit 1; }
+          echo '${{ needs.check-commit.result }}' | grep -xE 'success|skipped' || { echo 'Job "check-commit" failed' >&2; exit 1; }
+          echo '${{ needs.check-commits-dispatcher.result }}' | grep -xE 'success|skipped' || { echo 'Job "check-commits-dispatcher" failed' >&2; exit 1; }
+          echo '${{ needs.error-prone-checks.result }}' | grep -xE 'success|skipped' || { echo 'Job "error-prone-checks" failed' >&2; exit 1; }
+          echo '${{ needs.hive-tests.result }}' | grep -xE 'success|skipped' || { echo 'Job "hive-tests" failed' >&2; exit 1; }
+          echo '${{ needs.maven-checks.result }}' | grep -xE 'success|skipped' || { echo 'Job "maven-checks" failed' >&2; exit 1; }
+          echo '${{ needs.pt.result }}' | grep -xE 'success|skipped' || { echo 'Job "pt" failed' >&2; exit 1; }
+          echo '${{ needs.redshift-cloud-tests.result }}' | grep -xE 'success|skipped' || { echo 'Job "redshift-cloud-tests" failed' >&2; exit 1; }
+          echo '${{ needs.redshift-fte-tests.result }}' | grep -xE 'success|skipped' || { echo 'Job "redshift-fte-tests" failed' >&2; exit 1; }
+          echo '${{ needs.salesforce-tests.result }}' | grep -xE 'success|skipped' || { echo 'Job "salesforce-tests" failed' >&2; exit 1; }
+          echo '${{ needs.snowflake-nightly-tests.result }}' | grep -xE 'success|skipped' || { echo 'Job "snowflake-nightly-tests" failed' >&2; exit 1; }
+          echo '${{ needs.snowflake-weekly-tests.result }}' | grep -xE 'success|skipped' || { echo 'Job "snowflake-weekly-tests" failed' >&2; exit 1; }
+          echo '${{ needs.starburst-functions-ai-tests.result }}' | grep -xE 'success|skipped' || { echo 'Job "starburst-functions-ai-tests" failed' >&2; exit 1; }
+          echo '${{ needs.synapse-nightly-tests.result }}' | grep -xE 'success|skipped' || { echo 'Job "synapse-nightly-tests" failed' >&2; exit 1; }
+          echo '${{ needs.synapse-weekly-tests.result }}' | grep -xE 'success|skipped' || { echo 'Job "synapse-weekly-tests" failed' >&2; exit 1; }
+          echo '${{ needs.test.result }}' | grep -xE 'success|skipped' || { echo 'Job "test" failed' >&2; exit 1; }
+          echo '${{ needs.test-jdbc-compatibility.result }}' | grep -xE 'success|skipped' || { echo 'Job "test-jdbc-compatibility" failed' >&2; exit 1; }
+          echo '${{ needs.test-other-modules.result }}' | grep -xE 'success|skipped' || { echo 'Job "test-other-modules" failed' >&2; exit 1; }
