Filter out ci jobs when docs-only changes
(cherry picked from commit 3698755cc25d6ae37f2345134878b43453cd247c)
(cherry picked from commit fa1a8b808ddd4bf6e2b43df61424af1adb2e683c)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -54,6 +54,19 @@ concurrency:
     commit_sha=${{ github.event_name != 'pull_request' && github.event_name != 'repository_dispatch' && github.sha || 'NA' }}
   cancel-in-progress: true
 jobs:
+  path-filters:
+    runs-on: [self-hosted, gha-fleet-ec2-4cpu-16gb-amd64, latest]
+    outputs:
+      docs: ${{ steps.filter.outputs.docs }}
+      non_docs: ${{ steps.filter.outputs.non_docs }}
+    steps:
+      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3
+        id: filter
+        with:
+          filters: |
+            docs: 'docs/**'
+            non_docs: '!docs/**'
+
   maven-checks:
     runs-on: [self-hosted, gha-fleet-ec2-4cpu-16gb-amd64, latest]
     name: maven-checks ${{ matrix.java-version }}
@@ -99,6 +112,8 @@ jobs:
         run: rm -rf ~/.m2/repository/io/trino/trino-*
 
   artifact-checks:
+    needs: path-filters
+    if: needs.path-filters.outputs.non_docs == 'true'
     runs-on: [self-hosted, gha-fleet-ec2-4cpu-16gb-amd64, latest]
     timeout-minutes: 60
     steps:
@@ -143,8 +158,9 @@ jobs:
         run: core/docker/build.sh
 
   check-commits-dispatcher:
+    needs: path-filters
+    if: github.event_name == 'pull_request' && needs.path-filters.outputs.non_docs == 'true'
     runs-on: [self-hosted, gha-fleet-ec2-2cpu-8gb-amd64, latest]
-    if: github.event_name == 'pull_request'
     outputs:
       matrix: ${{ steps.set-matrix.outputs.matrix }}
     steps:
@@ -203,6 +219,8 @@ jobs:
           base_ref: ${{ github.event.pull_request.base.ref }}
 
   error-prone-checks:
+    needs: path-filters
+    if: needs.path-filters.outputs.non_docs == 'true'
     runs-on: [self-hosted, gha-fleet-ec2-4cpu-16gb-amd64, latest]
     timeout-minutes: 90
     steps:
@@ -237,6 +255,8 @@ jobs:
             -pl '!:trino-docs,!:trino-server'
 
   test-jdbc-compatibility:
+    needs: path-filters
+    if: needs.path-filters.outputs.non_docs == 'true'
     runs-on: [self-hosted, gha-fleet-ec2-16cpu-64gb-amd64, latest]
     timeout-minutes: 30
     steps:
@@ -287,6 +307,8 @@ jobs:
           upload-heap-dump: ${{ env.SECRETS_PRESENT == '' && github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository }}
 
   hive-tests:
+    needs: path-filters
+    if: needs.path-filters.outputs.non_docs == 'true'
     runs-on: [self-hosted, gha-fleet-ec2-4cpu-16gb-amd64, latest]
     strategy:
       fail-fast: false
@@ -1094,6 +1116,8 @@ jobs:
             :boom: Snowflake nightly tests failed on branch: ${{ steps.should_notify.outputs.branch }} (<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|see CI job for details>) (:thumbsup: this message if you take care of this)
 
   test-other-modules:
+    needs: path-filters
+    if: needs.path-filters.outputs.non_docs == 'true'
     runs-on: [self-hosted, gha-fleet-ec2-16cpu-64gb-amd64, latest]
     timeout-minutes: 60
     steps:
@@ -1270,6 +1294,8 @@ jobs:
           upload-heap-dump: ${{ env.SECRETS_PRESENT == '' && github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository }}
 
   build-test-matrix:
+    needs: path-filters
+    if: needs.path-filters.outputs.non_docs == 'true'
     runs-on: [self-hosted, gha-fleet-ec2-2cpu-8gb-amd64, latest]
     outputs:
       matrix: ${{ steps.set-matrix.outputs.matrix }}
@@ -1808,6 +1834,8 @@ jobs:
           github_token: ${{ secrets.GITHUB_TOKEN }}
 
   build-pt:
+    needs: path-filters
+    if: needs.path-filters.outputs.non_docs == 'true'
     runs-on: [self-hosted, gha-fleet-ec2-2cpu-8gb-amd64, latest]
     outputs:
       matrix: ${{ steps.set-matrix.outputs.matrix }}
@@ -2251,6 +2279,7 @@ jobs:
       - error-prone-checks
       - hive-tests
       - maven-checks
+      - path-filters
       - pt
       - redshift-cloud-tests
       - redshift-fte-tests
@@ -2275,6 +2304,7 @@ jobs:
           echo '${{ needs.error-prone-checks.result }}' | grep -xE 'success|skipped' || { echo 'Job "error-prone-checks" failed' >&2; exit 1; }
           echo '${{ needs.hive-tests.result }}' | grep -xE 'success|skipped' || { echo 'Job "hive-tests" failed' >&2; exit 1; }
           echo '${{ needs.maven-checks.result }}' | grep -xE 'success|skipped' || { echo 'Job "maven-checks" failed' >&2; exit 1; }
+          echo '${{ needs.path-filters.result }}' | grep -xE 'success|skipped' || { echo 'Job "path-filters" failed' >&2; exit 1; }
           echo '${{ needs.pt.result }}' | grep -xE 'success|skipped' || { echo 'Job "pt" failed' >&2; exit 1; }
           echo '${{ needs.redshift-cloud-tests.result }}' | grep -xE 'success|skipped' || { echo 'Job "redshift-cloud-tests" failed' >&2; exit 1; }
           echo '${{ needs.redshift-fte-tests.result }}' | grep -xE 'success|skipped' || { echo 'Job "redshift-fte-tests" failed' >&2; exit 1; }
